### ISSUE TITLE
原qq接口不能用了，我找了一个新接口,有几个参数不知道干嘛的

### ISSUE THREAD

**Issue by ziru-w** [noneplugin/nonebot-plugin-simplemusic#3]
from time import time
async def search_qq(keyword: str) -> Union[str, MessageSegment]:
    # url = "https://c.y.qq.com/soso/fcgi-bin/client_search_cp"
    headers={"User-Agent":'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.39',
    'Referer':'https://y.qq.com/'}
    reqTime=int(time()*1000)
    url='https://c.y.qq.com/splcloud/fcgi-bin/smartbox_new.fcg?_={reqTime}&cv=4747474&ct=24&format=json&inCharset=utf-8&outCharset=utf-8&notice=0&platform=yqq.json&needNewCode=1&uin=0&g_tk_new_20200303=5381&g_tk=5381&hostUin=0&is_xml=0&key='+keyword
    # params = {"p": 1, "n": 1, "w": keyword, "format": "json"}
    async with httpx.AsyncClient() as client:
        resp = await client.get(url,headers=headers)#, params=params
        # print(resp.text)
        result = json.loads(resp.text)
        # result["data"]["song"]["list"]
        # songs[0]["songid"]
    if songs := result["data"]["song"]["itemlist"]:
        print(songs[0])
        return MessageSegment.music("qq", songs[0]["id"])
    return "QQ音乐中找不到相关的歌曲"

**Comment by MeetWq** [comment]
我试了现在的可以用啊

**Comment by ziru-w** [comment]
哦好的，上个月更新，我看旁边好久没更新，以为没有换接口，嘿嘿。
我以为还是"https://c.y.qq.com/soso/fcgi-bin/client_search_cp"
我找的这个接口就是现在的接口
