### ISSUE TITLE
qq点歌失效

### ISSUE THREAD

**Issue by rainyorange** [noneplugin/nonebot-plugin-simplemusic#4]
![image](https://user-images.githubusercontent.com/36807368/197882668-c9a1af06-53be-477c-8ab3-f7d74c2fb204.png)

**Comment by MeetWq** [comment]
你用的是最新版吗

**Comment by rainyorange** [comment]
是啊 我还卸载重新装了一次

**Comment by MeetWq** [comment]
我这边是没问题的
pip show nonebot_plugin_simplemusic 看看版本

**Comment by rainyorange** [comment]
诶 为什么重复安装还是旧版本

**Comment by rainyorange** [comment]
哦 我知道了 用的install 不是upgrade 抱歉
