### ISSUE TITLE
b站、酷我点歌已经挂了

### ISSUE THREAD

**Issue by bhshuya** [noneplugin/nonebot-plugin-simplemusic#7]
onebot版本：2.0.0rc4

![image](https://user-images.githubusercontent.com/77972386/232994575-89f6462b-a037-496e-b4e2-2c3cbe4d768a.png)
![image](https://user-images.githubusercontent.com/77972386/232994660-505f70fe-9832-435e-814d-ef60beae149c.png)
酷我
![image](https://user-images.githubusercontent.com/77972386/232996807-8ef1aa73-089e-4dc3-a3d1-2ee6d866c38d.png)

**Comment by bhshuya** [comment]
![image](https://user-images.githubusercontent.com/77972386/232998338-d9fe45c2-2e6a-4715-84e1-d2eaab62fa8d.png)

**Comment by MeetWq** [comment]
酷我的报错是因为部分歌需要付费，正常歌曲是没问题的

b站是gocq的问题：https://github.com/Mrs4s/go-cqhttp/issues/1495
暂时没法解决，目前改为直接发送链接文本
